### ISSUE TITLE
[Bug Tracker] atmospherePro bugs/enhancements

### ISSUE THREAD

**Issue by Sardar1208** [atsign-foundation/atmosphere_pro#286]

**Comment by Sardar1208** [comment]
- [x] - there’s what looks like a yellow share icon next to the download button when someone receives a file. Pressing it does nothing. What’s it for?
- [x] there is currently no way to send images or videos via the gallery on iOS. I can only select from “my files” 
- [x] when looking at my files… some images didn’t have thumbnails and the video icon is oddly cropped
- [x] when adding a contact, it says “atsign Valid” regardless of what I type. Including multiple words. What is the criteria for a valid atsign in this instance?
- [x] when looking at history, could we make the selectors for sent/received a little bigger as people with larger fingers will struggle with the selections. Also when you initially select the page it’s unclear whether you are looking at sent or received because neither is selected 
- [x] if you send something to multiple people, the history only shows one person… and there is not way of seeing whether the item was received/downloaded by each recipient (this is present in the old design) 
- [x] we will need to go through the wording for error messages and stuff.. I saw a typo when adding a non existent contact. Could we please have all the strings for errors and confirmations  in a file that we can edit and send back? 
- [x] in the new design we have also lost the information about what the app is doing during send and download..eg encrypting, uploading… decrypting etc 
- [x] update the splash screen

**Comment by sonle-geekyants** [comment]
Error text:
https://docs.google.com/document/d/1fmC68hflgTYOHMw87LtUXecF-OmZK8mBjFHSF07fYS0/edit

**Comment by Dariamarg** [comment]
Can we switch out the splash screen to: 
- [Figma](https://www.figma.com/file/eKGFZ2t0hi03LT07n1Fx36/AtmospherePro-V2?type=design&node-id=429%3A9599&t=xeTlPg8Cl1HtJbxi-1)
<img width="241" alt="Screenshot 2023-06-08 at 12 25 40 PM" src="https://github.com/atsign-foundation/atmosphere_pro/assets/84993403/96c085a1-784e-48de-9afe-2f3dfaf9b871">

**Comment by ksanty** [comment]
> Can we switch out the splash screen to:
> 
> * [Figma](https://www.figma.com/file/eKGFZ2t0hi03LT07n1Fx36/AtmospherePro-V2?type=design&node-id=429%3A9599&t=xeTlPg8Cl1HtJbxi-1)
> 
> <img alt="Screenshot 2023-06-08 at 12 25 40 PM" width="241" src="https://user-images.githubusercontent.com/84993403/244446094-96c085a1-784e-48de-9afe-2f3dfaf9b871.png">

Ohhhhh love that @Dariamarg

**Comment by Sardar1208** [comment]
"in the new design we have also lost the information about what the app is doing during send and download..eg encrypting, uploading… decrypting etc"

In this case, we are showing encrypting, uploading messages when we send a file. Sometimes in case of small files like images the process happens really fast so you might miss it. But if you try to send a large file like video, then you see all the appropriate messages.

@Dariamarg  In case of download, the design only shows a circular progress indicator over an icon. So, we cant show messages there.

**Comment by sonle-geekyants** [comment]
This issue related to this PR: https://github.com/atsign-foundation/atmosphere_pro/issues/289

**Comment by tinashe404** [comment]
I've tested the items from the checklist that i reported.. some are fixed and some not quite. Do you want the bugs to be added to this ticket?

**Comment by ksanty** [comment]
Not sure what the rest of the team thinks @tinashe404. My 2 cents, might be good to have them here, but hate to create redundancy if they are living elsewhere.

**Comment by Sardar1208** [comment]
@tinashe404 @ksanty Can you uncheck items that are not fixed from the above list?

**Comment by Sardar1208** [comment]
@ksanty @Dariamarg I think this ticket can be closed now. What do you think ? or should we backlog this ?

**Comment by Dariamarg** [comment]
I think it's good to close 
The only note is the encryption messaging that we don't yet have but we have tickets for the skeleton load (Im sure we can fit a place for text in there), what do you think? @Sardar1208

**Comment by sachins-geekyants** [comment]
@Dariamarg @Sardar1208 can you mention skeleton ticket here.
This ticket can be closed now.

**Comment by Dariamarg** [comment]
https://github.com/atsign-foundation/apps/issues/808
